name: tests

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Quick smoke run (small graph)
        run: |
          mkdir -p data/seeds figures
          python sim/graph_generators.py --dim 4 --N 5000 --seed 0 --out data/seeds/g_small.npz
          python sim/poincare_check.py --graph data/seeds/g_small.npz --samples 2 --out figures/fig_poincare_ratio_ci.png

      - name: Run tests
        run: |
          pytest -q
