name: tests

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 👉 ICI on ajoute le cache pip pour accélérer les runs
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 👉 Vérifie que les imports du package sim fonctionnent
      - name: Smoke import
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          python - <<'PY'
          import os
          print("PYTHONPATH=", os.environ.get("PYTHONPATH"))
          import sim.graph_generators, sim.poincare_check, sim.gamma_convergence, sim.hyperbolicity_test
          print("SIM imports OK")
          PY

      # 👉 Petite exécution de démo pour générer une figure
      - name: Quick smoke run (small graph)
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          mkdir -p data/seeds figures
          python sim/graph_generators.py --dim 4 --N 5000 --seed 0 --out data/seeds/g_small.npz
          python sim/poincare_check.py --graph data/seeds/g_small.npz --samples 2 --out figures/fig_poincare_ratio_ci.png

      # 👉 Tests unitaires
      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: pytest -q

      # 👉 Publie les figures en artefacts CI (toujours, même si tests KO)
      - name: Upload figures
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: figures
          path: figures/*
          if-no-files-found: ignore
